# Search methods

import search

ab = search.GPSProblem('A', 'B', search.romania)
print("Resolución ejercicio 1a: Cola")
print(search.breadth_first_graph_search(ab))
print("Resolución ejercicio 1b: Pila")
print(search.depth_first_graph_search(ab))
print("Resolución ejercicio 1c: Camino óptimo")
print(search.bab(ab))
print("Resolución ejercicio 1d: Camino óptimo con heurística (subestimación)")
print(search.ras(ab))
print()

oe = search.GPSProblem('O', 'E', search.romania)
print("Resolución ejercicio 2a: Cola")
print(search.breadth_first_graph_search(oe))
print("Resolución ejercicio 2b: Pila")
print(search.depth_first_graph_search(oe))
print("Resolución ejercicio 2c: Camino óptimo")
print(search.bab(oe))
print("Resolución ejercicio 2d: Camino óptimo con heurística (subestimación)")
print(search.ras(oe))
print()

oe = search.GPSProblem('O', 'E', search.romania)
print("Resolución ejercicio 2a: Cola")
print(search.breadth_first_graph_search(oe))
print("Resolución ejercicio 2b: Pila")
print(search.depth_first_graph_search(oe))
print("Resolución ejercicio 2c: Camino óptimo")
print(search.bab(oe))
print("Resolución ejercicio 2d: Camino óptimo con heurística (subestimación)")
print(search.ras(oe))
print()

pz = search.GPSProblem('P', 'Z', search.romania)
print("Resolución ejercicio 3a: Cola")
print(search.breadth_first_graph_search(pz))
print("Resolución ejercicio 3b: Pila")
print(search.depth_first_graph_search(pz))
print("Resolución ejercicio 3c: Camino óptimo")
print(search.bab(pz))
print("Resolución ejercicio 3d: Camino óptimo con heurística (subestimación)")
print(search.ras(pz))
print()

ls = search.GPSProblem('L', 'S', search.romania)
print("Resolución ejercicio 4a: Cola")
print(search.breadth_first_graph_search(ls))
print("Resolución ejercicio 4b: Pila")
print(search.depth_first_graph_search(ls))
print("Resolución ejercicio 4c: Camino óptimo")
print(search.bab(ls))
print("Resolución ejercicio 4d: Camino óptimo con heurística (subestimación)")
print(search.ras(ls))
print()

bl = search.GPSProblem('B', 'L', search.romania)
print("Resolución ejercicio 5a: Cola")
print(search.breadth_first_graph_search(bl))
print("Resolución ejercicio 5b: Pila")
print(search.depth_first_graph_search(bl))
print("Resolución ejercicio 5c: Camino óptimo")
print(search.bab(bl))
print("Resolución ejercicio 5d: Camino óptimo con heurística (subestimación)")
print(search.ras(bl))
print()
