# Search methods

import search

ab = search.GPSProblem('A', 'B', search.romania)
print("A - B")
print("Breadth first")
print(search.breadth_first_graph_search(ab))
print("Depth first")
print(search.depth_first_graph_search(ab))
print("Branch and Bound")
print(search.bab(ab))
print("Branch and Bound (subestimation)")
print(search.ras(ab))
print()

oe = search.GPSProblem('O', 'E', search.romania)
print("O - E")
print("Breadth first")
print(search.breadth_first_graph_search(oe))
print("Depth first")
print(search.depth_first_graph_search(oe))
print("Branch and Bound")
print(search.bab(oe))
print("Branch and Bound (subestimation)")
print(search.ras(oe))
print()

pz = search.GPSProblem('P', 'Z', search.romania)
print("P - Z")
print("Breadth first")
print(search.breadth_first_graph_search(pz))
print("Depth first")
print(search.depth_first_graph_search(pz))
print("Branch and Bound")
print(search.bab(pz))
print("Branch and Bound (subestimation)")
print(search.ras(pz))
print()

ls = search.GPSProblem('L', 'S', search.romania)
print("L - S")
print("Breadth first")
print(search.breadth_first_graph_search(ls))
print("Depth first")
print(search.depth_first_graph_search(ls))
print("Branch and Bound")
print(search.bab(ls))
print("Branch and Bound (subestimation)")
print(search.ras(ls))
print()

bl = search.GPSProblem('B', 'L', search.romania)
print("B - L")
print("Breadth first")
print(search.breadth_first_graph_search(bl))
print("Depth first")
print(search.depth_first_graph_search(bl))
print("Branch and Bound")
print(search.bab(bl))
print("Branch and Bound (subestimation)")
print(search.ras(bl))
print()